### ISSUE TITLE
cant use No Bling, always get wrong path

### ISSUE THREAD

**Issue by RmbGuts** [No-Bling/DOTA#46] opened 2020-06-11 09:40 UTC
My game in C  disk idk why this app always chose wrong path 
![nobling](https://user-images.githubusercontent.com/66776595/84370267-b4a5a500-abe0-11ea-877b-ac4e3ab73fc4.png) maybe someone of use knows how i can fix it

**Comment by RmbGuts** [comment] 2020-06-11 09:41
also i try to move dota in disk D but i have Error with 0

**Comment by RmbGuts** [comment] 2020-06-11 09:43
btw my nobling still work if i have -tempcontent ON

**Comment by KerzaGG** [comment] 2020-06-13 00:12
@RmbGuts You should wait, after the battlepass the mod is not working anyway. Check #43 Aveyo has commented on it.

**Comment by Lethalmathematix** [comment] 2020-06-15 10:43
I generated a new build using the old script and it seems to work fine for me.

Attaching it here if you want to give it a go.

[pak01_dir.vpk.zip](https://github.com/No-Bling/DOTA/files/4779705/pak01_dir.vpk.zip)

**Comment by ganimtaer** [comment] 2020-06-16 12:03
> 
> 
> I generated a new build using the old script and it seems to work fine for me.
> 
> Attaching it here if you want to give it a go.
> 
> [pak01_dir.vpk.zip](https://github.com/No-Bling/DOTA/files/4779705/pak01_dir.vpk.zip)

Sorry, but could you write the detailed paths and how to include your No Bling file. on a clean client D2?

**Comment by KerzaGG** [comment] 2020-06-17 02:36
@ganimtaer you have to copy that file and paste it/overwrite the one inside the original no-bling file you downloaded, then run the script.

**Comment by ganimtaer** [comment] 2020-06-17 09:58
> 
> 
> @ganimtaer you have to copy that file and paste it/overwrite the one inside the original no-bling file you downloaded, then run the script.

The problem is that no bling is currently removed from this site. and I now had a "clean client" DotA 2 .. that is - I did not install no bling until this moment.

**Comment by ganimtaer** [comment] 2020-06-17 10:05
> 
> 
> @ganimtaer you have to copy that file and paste it/overwrite the one inside the original no-bling file you downloaded, then run the script.

It helped me to create a directory in steamapps \ common \ dota 2 beta \ game.

folder under the name "dota_tempcontent" and put the file there above (pak01_dir.vpk)

and write "-tempcontent". in the launch options for DotA 2

Sorry for my bad english, I'm from Kazakhstan. and use google translator :)

**Comment by Lethalmathematix** [comment] 2020-06-17 10:05
No need to run the script.

> #### How to manually install No-Bling DOTA mod builds in 2019:

> ~ CREATE FOLDER \steamapps\common\dota 2 beta\game\dota_tempcontent
> ~ COPY pak01_dir.vpk IN \steamapps\common\dota 2 beta\game\dota_tempcontent
> ~ ADD LAUNCH OPTION: -tempcontent

> If you have trouble locating the path, right-click Dota 2 in Steam Library window - Properties - Local files - Browse local files
That should lead you to \steamapps\common\dota 2 beta
Enter game subfolder, then create folder dota_tempcontent and copy pak01_dir.vpk in there

**Comment by ganimtaer** [comment] 2020-06-17 10:14
> 
> 
> No need to run the script.
> 
> > #### How to manually install No-Bling DOTA mod builds in 2019:
> 
> > ~ CREATE FOLDER \steamapps\common\dota 2 beta\game\dota_tempcontent
> > ~ COPY pak01_dir.vpk IN \steamapps\common\dota 2 beta\game\dota_tempcontent
> > ~ ADD LAUNCH OPTION: -tempcontent
> 
> > If you have trouble locating the path, right-click Dota 2 in Steam Library window - Properties - Local files - Browse local files
> > That should lead you to \steamapps\common\dota 2 beta
> > Enter game subfolder, then create folder dota_tempcontent and copy pak01_dir.vpk in there

Yes, yes, that’s exactly what I was looking for. but it dawned on me a little earlier than you had time to answer. but thanks a lot anyway!)

**Comment by Lethalmathematix** [comment] 2020-06-17 11:18
Haha

No problem.

Looks like we posted within a couple of seconds of each other! :)

**Comment by Lethalmathematix** [comment] 2020-06-17 11:19
Haha

Looks like we posted within a couple of seconds of each other! :)

**Comment by KerzaGG** [comment] 2020-06-17 11:23
@Lethalmathematix Thank you for helping ganimtaer, I had a looong day my bad! Also does your build has the minimap icons for Void Spirit and Snapfire?

**Comment by Lethalmathematix** [comment] 2020-06-17 11:43
He pretty much helped himself. :p


It doesn't.

I didn't bother with it because I play with the arrow icons on minimap.

**Comment by ganimtaer** [comment] 2020-06-18 09:50
> 
> 
> Haha
> 
> Looks like we posted within a couple of seconds of each other! :)

Exactly :)

Your file - it works for me, only the new Arcana item for QoP is displayed incorrectly. xD

**Comment by AveYo** [comment] 2020-06-18 21:41
Intriguing proposal about the river - climate change affecting DOTA :)   
But I don't think it's possible as it's a feature of the map itself and you're not allowed to touch stuff inside the dota.vpk   
What works instead is to use another terrain such as the Reef's Edge.   
In other news TI 10 is closing in on 16.000.000 :)

**Comment by Lethalmathematix** [comment] 2020-06-18 23:33
Aww yiss! Hail Lord Gaben!!!💰💰💰🎅💰💰💰

@AveYo: How do the river vials work? Would it be possible to use the "River Vial: Dry" texture as default? Or is that located under dota.vpk too?

@ganimtaer: Sorry. I haven't played in a while so my Dota 2 wasn't updated. Here's the build without QoP arcana: [pak01_dir.vpk.zip](https://github.com/No-Bling/DOTA/files/4801687/pak01_dir.vpk.zip)

**Comment by AveYo** [comment] 2020-06-19 01:26
Vials are set as `hero_ability`, you most likely can't force one without actually being activated by you or someone else on the map. Old script did support turning most of them off tough.   

BP has lost momentum.. Pudge persona soon I guess. Then I attack!

**Comment by KerzaGG** [comment] 2020-06-19 01:29
Everyone is gonna go crazy with both pudge and anti-mage persona. Also I don't know if the River Vial Dry would be worth. Don't know if it actually makes the river disappear to save resources or just make it transparent.

**Comment by ganimtaer** [comment] 2020-06-19 12:44
> 
> 
> Aww yiss! Hail Lord Gaben!!!💰💰💰🎅💰💰💰
> 
> @AveYo: How do the river vials work? Would it be possible to use the "River Vial: Dry" texture as default? Or is that located under dota.vpk too?
> 
> @ganimtaer: Sorry. I haven't played in a while so my Dota 2 wasn't updated. Here's the build without QoP arcana: [pak01_dir.vpk.zip](https://github.com/No-Bling/DOTA/files/4801687/pak01_dir.vpk.zip)

Thank you so much - for your work! :)

**Comment by Lethalmathematix** [comment] 2020-06-21 18:55
I just press a button.

Based @AveYo should get all the thanks. :D

**Comment by ganimtaer** [comment] 2020-06-22 11:34
> 
> 
> I just press a button.
> 
> Based @AveYo should get all the thanks. :D

Dear @Lethalmathematix and @AveYo, what landscape do you think has the highest and best performance and gives the highest FPS - even more than standard (no terrain)?

**Comment by KerzaGG** [comment] 2020-06-24 09:52
What does landscape means in this context?

**Comment by ganimtaer** [comment] 2020-06-24 14:47
> 
> 
> What does landscape means in this context?

https://dota2-ru.gamepedia.com/%D0%9B%D0%B0%D0%BD%D0%B4%D1%88%D0%B0%D1%84%D1%82%D1%8B

**Comment by AveYo** [comment] 2020-07-08 00:07
I have closed all the old issues, feel free to create others for the new script

**Closed by AveYo** 2020-07-08 00:07 UTC
