### ISSUE TITLE
Is there a way to filter models in "Glance" AKA Gabening mode?

### ISSUE THREAD

**Issue by ryamshin** [No-Bling/DOTA#28] opened 2019-08-26 03:54 UTC
As a test I tried adding  
"10091" "#"
in the "Glance" {} section. 10091 should be Baby Roshan, but when I enter the game, Baby Roshan is still the Dire courier.

**Comment by AveYo** [comment] 2019-09-19 04:39
It's incomplete and bugged.  
Custom filtering needs refactoring badly - for starters the personal file should only need the specific filters, not be a complete duplicate of the "official" one. TODO

**Comment by AveYo** [comment] 2020-07-07 23:21
Well, it's happening.  
Note that GlanceValue no longer affects couriers.

**Closed by AveYo** 2020-07-07 23:21 UTC
